"""Added and removed some columns

Revision ID: 2ddd8a0f9e70
Revises: bed56e7bdeb0
Create Date: 2024-07-12 08:50:06.743663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddd8a0f9e70'
down_revision = 'bed56e7bdeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('services')
    
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.alter_column('bill_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
