"""remove date type datatype from patients table

Revision ID: b78c474e7eda
Revises: c72a09b6ed3a
Create Date: 2024-07-10 23:05:23.830845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78c474e7eda'
down_revision = 'c72a09b6ed3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
